### ISSUE TITLE
Examples: contain "unexpected keyword argument 'max_targets' "

### ISSUE THREAD

**Issue by kjlockhart** [zakird/celerybeat-mongo#2]
see: my pull request.

[2014-06-24 10:18:44,237: ERROR/MainProcess] Task tasks1.add[dc50a2f3-a012-4245-b24a-1b79db4f15dd] raised unexpected: TypeError("add
() got an unexpected keyword argument 'max_targets'",)
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\celery\app\trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "C:\Python27\lib\site-packages\celery\app\trace.py", line 437, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: add() got an unexpected keyword argument 'max_targets'

**Comment by zakird** [comment]
I believe this was fixed by pull request in 2014; closing.
